#!/bin/bash
#sig term/quit handler to umount what we've mounted
# take from: http://www.linuxjournal.com/content/use-bash-trap-statement-cleanup-temporary-files
declare -a on_exit_items
function on_exit()
{
    for i in "${on_exit_items[@]}"
    do
        log_debug "running on_exit: $i"
        eval $i
    done
}
 
function add_on_exit()
{
    local n=${#on_exit_items[*]}
    on_exit_items[$n]="$*"
    if [[ $n -eq 0 ]]; then
        log_debug "add_on_exit called, setting on_exit trap"
        trap on_exit EXIT
    fi
}

